### ISSUE TITLE
Esposizione testo del filetto es.4 con possibile ambiguita'

### ISSUE THREAD

**Issue by ivanopagano** [CodeGardenRome/esercizi-funzionali-graduali#12]
```
Ad esempio, data la matrice: 

[ [" ", "O", "X"],
  [" ", "X", "O"],
  ["X", " ", " "] ]

Se la cella di partenza è [1,0] e la funzione successore è quella delle righe,
la funzione generaVettore dovrà restituire il vettore:

[" ","X","O"]
```

nel testo non e' chiaro quale sia la `funzione successore delle righe` o almeno puo' essere fuorviante, perche' nell'esercizio precedente si parla di

`cellaSuccessivaRighe([0,0]) = [1,0]`

dove viene incrementato l'indice di riga, che per questo esercizio va a selezionare una colonna.

Suggerirei di riformulare il testo per ridurre l'ambiguita', o rinominare il nome delle funzioni dell'es.3 per meglio combaciare con il testo di questo esercizio?

**Comment by vitalijzad** [comment]
Sì, in effetti andrebbe spiegato molto meglio. Ci pensi tu a dargli una sistemata?
